name: Docker CI/CD

on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t real-time-tracker .

    - name: Run Docker container
      run: |
        docker run -d -p 3000:3000 real-time-tracker

    - name: Test running container
      run: |
        # Wait for the container to be fully up and running
        sleep 10
        # Replace with your actual tests
        curl --fail http://localhost:3000 || exit 1
